### ISSUE TITLE
Fix pip-locations

### ISSUE THREAD

**Issue by whotwagner** [ait-aecid/aminer-ansible#6]
This roles uses  hardcoded paths to python-packages :
```
- name: Link python3-cerberus
  file:
    src: /usr/lib/python3.6/site-packages/cerberus
    dest: /etc/aminer/conf-enabled/cerberus
    state: link

- name: Link kafka
  file:
    src: /usr/lib/python3.6/site-packages/kafka
    dest: /etc/aminer/conf-enabled/kafka
    state: link

```
